#!/usr/bin/bash
########################################################################
#
# baseconv
# Convert numbers from one base to another
#
########################################################################

########################################################################
# Variables
FROM=10
TO=10

########################################################################
# Functions
PrintUsage() {
  echo "Convert numbers from one base to another

  Usage:
    baseconv from to number"
}

########################################################################
# Main

# Check Arguments
if [ "$#" -ne "3" ]
then
  echo "You need to enter 3 numbers."
  PrintUsage
  exit 1
else
  IBASE="${1^^}"   # ^^ = Uppercase
  OBASE="${2^^}"
  NUMBER="${3^^}"
fi

if ! [[ "$IBASE" =~ ^[0-9]+$ ]]
then
  echo "Input Base is not a number."
  PrintUsage
  exit 1
elif ! [[ "$OBASE" =~ ^[0-9]+$ ]]
then
  echo "Output Base is not a number."
  PrintUsage
  exit 1
elif ! [[ "$NUMBER" =~ ^[0-9]+$ ]]
then
  echo "Input Number is not a number."
  PrintUsage
  exit 1
fi

# Let's convert!
bc <<< "obase=$OBASE; ibase=$IBASE; $NUMBER"

# EOF
