#!/bin/bash
######################################################################
#
# bildschirm
# Bildschirme steuern und verwalten
#
# Copyright (c) 2011-2013 Emanuel Duss
# Licensed under GNU General Public License
#
######################################################################

######################################################################
# Variabeln
INTERN="LVDS1"
EXTERN="VGA1"
WAIT="2" # Sekunden

######################################################################
# Funktionen

PrintUsage(){
cat << EOI
Usage:
 bildschirm < modes | intern | extern | clone | extend >

Optionen:
  modes    Moegliche Modes ausgeben
  intern   Nur internen Bildschirm verwenden
  extern   Nur externer Bildschirm verwenden
  clone    Gleiche Ausgabe auf beiden Bildschirmen
  extend   Bild auf externem Bildschirm erweitern

EOI
}

######################################################################
# Main
case $1 in
  modes)
    xrandr -q
    ;;
  intern)
    xrandr --output "$INTERN" --auto --output "$EXTERN" --off
    ;;
  extern)
    xrandr --output "$INTERN" --off --output "$EXTERN" --auto
    ;;
  clone)
    CLONERES="`xrandr --query | awk '/^ *[0-9]*x[0-9]*/{ print $1 }' | sort -n | uniq -d | tail -1`"
    xrandr --output "$INTERN" --mode "$CLONERES" --output "$EXTERN" --same-as "$INTERN" --mode "$CLONERES"
    ;;
  extend)
     xrandr --output "$INTERN" --auto --pos 0x400 --output "$EXTERN" --auto --primary --pos 1280x0 --primary
     # --right-of $INTERN funktioniert nicht zusammen mit --pos
    ;;
  -h)
    PrintUsage
    exit
    ;;
  *)
    PrintUsage
    exit 1
    ;;
esac

if [ -f ~/.fehbg ]
then
  (sleep "$WAIT"
    eval `cat ~/.fehbg`
  ) &
fi

if pgrep conky &>/dev/null
then
  (sleep "$WAIT"
    pkill -HUP conky 2>&1 >/dev/null
  ) &
fi

# EOF
