#!/bin/bash
#
# ddns-updater - Update dynamic dns entries
#

CONF="${1:-/etc/ddns-updater.conf}"
. $CONF

if [[ -z "$KEYFILE" || -z "$NAMESERVER" || -z "$ZONE" \
   || -z "$HOSTNAME" || -z "$TTL" ]]
then
  echo "Error loading configuration file $CONF"
  exit 1
fi

IPADDR="${CUSTOMIP:-$(dig myip.opendns.com @resolver1.opendns.com +short)}"
IPADDROLD="$(dig $HOSTNAME @$NAMESERVER +short)"

if [[ "$IPADDR" == "$IPADDROLD" ]]
then
  exit
fi

(
  echo "server $NAMESERVER"
  echo "zone $ZONE"
  echo "update delete $HOSTNAME"
  echo "update add $HOSTNAME $TTL A $IPADDR"
  echo "send"
) | nsupdate -v -k $KEYFILE
