#!/usr/bin/env bash
#
# ddns-updater - Update dynamic dns entries
#

CONF="${1:-/etc/ddns-updater.conf}"
. "$CONF"

if [[ -z "$KEYFILE" || -z "$NAMESERVER" || -z "$ZONE" \
   || -z "$HOSTNAME" || -z "$TTL" ]]
then
  echo "Error loading configuration file $CONF"
  exit 1
fi

IPADDR="${CUSTOMIP:-$(curl -s -4 https://motd.ch/ip.php)}"
IPADDROLD="$(dig $HOSTNAME @$NAMESERVER +short)"
IP6ADDR="${CUSTOMIP6:-$(curl -s -6 https://motd.ch/ip.php)}"
IP6ADDROLD="$(dig $HOSTNAME AAAA @$NAMESERVER +short)"

if [[ "$IPADDR" == "$IPADDROLD" && "$IP6ADDR" == "$IP6ADDROLD" ]]
then
  exit
fi

(
  echo "server $NAMESERVER"
  echo "zone $ZONE"
  echo "update delete $HOSTNAME"
  echo "update add $HOSTNAME $TTL A $IPADDR"
  echo "update add $HOSTNAME $TTL AAAA $IP6ADDR"
  echo "send"
) | nsupdate -v -k "$KEYFILE"
