#!/usr/bin/env bash
########################################################################
#
# dyndnslogin
# Automate login to prevent account expiration
#
########################################################################

########################################################################
# DynDNS Settings (default-value, overwrite with $1 and $2)
# If you have special chars in your password, you need to urlencode:
# python -c "from urllib.parse import quote;
#   print(quote('your password', safe=''))"
DEFAULT_USERNAME="username"
DEFAULT_PASSWORD="password"


# Import settings from /etc/ddclient.conf if available
DDCONF="/etc/ddclient.conf"
if [ -r "$DDCONF" ] && grep -q "^server=members.dyndns.org" "$DDCONF"
then
    DEFAULT_USERNAME="`awk -F= '/^login=/{ print $2 }' $DDCONF`"
    DEFAULT_PASSWORD="`awk -F= '/^password=/{ print $2 }' $DDCONF`"
fi

########################################################################
# Variabeln
USERNAME=${1:-$DEFAULT_USERNAME}
PASSWORD=${2:-$DEFAULT_PASSWORD}

PROGNAME=dyndnslogin
COOKIE=`mktemp --tmpdir="/tmp" -t ${PROGNAME}_cookie_XXXXX`
OUTPUT=`mktemp --tmpdir="/tmp" -t ${PROGNAME}_output_XXXXX`
USERAGENT="Mozilla/5.0"

########################################################################
# Main

MULTIFORM=`curl -s -A $USERAGENT -c $COOKIE https://account.dyn.com \
  | awk -F\' '/multiform/{ print $6 }'`

curl -s --location -A "$USERAGENT" -b $COOKIE -c $COOKIE -o $OUTPUT \
  --data-urlencode "username=$USERNAME&password=$PASSWORD&iov_id=&submit=Log+in&multiform=$MULTIFORM" \
  https://account.dyn.com/

if grep -i -E "(Welcome|Hi).*$USERNAME" $OUTPUT > /dev/null 2>&1
then
  echo Login successful
else
  echo Login failed
  FAILED="true"
fi

rm $COOKIE
rm $OUTPUT

if [ "$FAILED" = "true" ]
then
  exit 1
fi

# EOF
