#!/bin/bash
########################################################################
#
# fehshow
# Öffnet alle Bilder im Verzeichnis statt nur ein Bild in feh
#
########################################################################


########################################################################
# Variabeln
FILETYPES='*.jpg *.png *.gif *.jpeg'

########################################################################
# Main

cd `dirname "$1"`
FILE=`basename "$1"`
feh -q $FILETYPES --auto-zoom --sort filename \
  --borderless --scale-down --draw-filename --image-bg black \
  --start-at "$FILE"

# EOF
