#!/bin/bash
#
# fehshow - Wrapper for feh for a nice image display
#

FILETYPES='*.jpg *.JPG *.png *.PNG *.gif *.GIF *.jpeg *.JPEG'

cd `dirname "$1"`
FILE=`basename "$1"`
feh -q $FILETYPES --auto-zoom --sort filename \
  --borderless --scale-down --draw-filename --image-bg black \
  --start-at "$FILE"
