#!/bin/bash
########################################################################
#
# hsrsync
# Synchronisiert Verzeichnisse der HSR
#
########################################################################

########################################################################
# Variabeln
DSTDIR="/home/emanuel/Daten/Studium/Semester_4_FS14_Skripteserver"
MNTDIR="/media/hsr_skripte"
SRCDIR="$MNTDIR/Informatik/Fachbereich/Challenge_Projekte/ChallP/ChallP-FS14-CyberSecurityTrainingsCamp \
  $MNTDIR/Informatik/Fachbereich/Datenbanksysteme_2/Dbs2 \
  $MNTDIR/Informatik/Fachbereich/Informationssicherheit_1_-_Grundlagen/InfSi1 \
  $MNTDIR/Informatik/Fachbereich/Parallele_Programmierung/ParProg \
  $MNTDIR/Mathematik_Naturwissenschaften/Physik_4_fuer_Informatiker \
  $MNTDIR/Informatik/Fachbereich/Software-Engineering_2/SE2 \
  $MNTDIR/Informatik/Fachbereich/Verteilte_SW-Systeme/Vss \
  $MNTDIR/Kommunikation_Wirtschaft_Recht/Volkswirtschaft_und_Technikgeschichte"

########################################################################
# Main
if ! mountpoint "$MNTDIR" > /dev/null 2>&1
then
  echo "$MNTDIR ist nicht gemountet. Mounte..."
  if ! mount "$MNTDIR"
  then
    echo "Fehler: Verzeichnis $MNTDIR kann nicht gemountet werden!"
    exit 1
  fi
fi

if ! [ -d "$DSTDIR" ]
then
  echo "$DSTDIR existiert nicht"
  exit 1
fi

rsync -ahvz --progress --delete --exclude "*.lnk" --exclude "Desktop.ini" \
  --exclude "Thumbs.db" --exclude ".DS_Store" --exclude "Vss/2013" \
  --exclude "Dbs2/Admin/FS1[123]" --exclude "sqldeveloper-2*" \
  $SRCDIR "$DSTDIR"

if umount $MNTDIR >/dev/null 2>&1
then
  echo "$MNTDIR wurde ausgehängt"
else
  echo "$MNTDIR bleibt gemountet"
fi

echo Totale Grösse:
du -hs "$DSTDIR"

# EOF
