#!/bin/bash
########################################################################
#
# hsrsync
# Synchronisiert Verzeichnisse der HSR
#
########################################################################

########################################################################
# Variabeln
DSTDIR="/home/emanuel/Daten/Studium/Semester_3_HS13_Skripteserver"
MNTDIR="/media/hsr_skripte"
SRCDIR="$MNTDIR/Mathematik_Naturwissenschaften/Physik_1/Ph1Mech/Cossmann \
  $MNTDIR/Mathematik_Naturwissenschaften/Wahrscheinlichkeitsrechnung_und_Statistik/WrStat \
  $MNTDIR/Informatik/Fachbereich/Programmieren_3_C++11/Prog3 \
  $MNTDIR/Informatik/Fachbereich/Software-Engineering_1/SE1 \
  $MNTDIR/Informatik/Fachbereich/Informations-_und_Codierungstheorie/ICTh \
  $MNTDIR/Informatik/Fachbereich/User_Interfaces_1/UInt1 \
  $MNTDIR/Informatik/Fachbereich/Datenbanksysteme_1/Dbs1 \
  $MNTDIR/Kommunikation_Wirtschaft_Recht/Rhetorische_Kommunikation_fuer_IngenieurInnen/RKI/Bohr"

########################################################################
# Main
if ! mountpoint "$MNTDIR" > /dev/null 2>&1
then
  echo "$MNTDIR ist nicht gemountet. Mounte..."
  if ! mount "$MNTDIR"
  then
    echo "Fehler: Verzeichnis $MNTDIR kann nicht gemountet werden!"
    exit 1
  fi
fi

if ! [ -d "$DSTDIR" ]
then
  echo "$DSTDIR existiert nicht"
  exit 1
fi

rsync -ahvz --progress --delete --exclude "*.lnk" --exclude "Desktop.ini" \
  --exclude "Thumbs.db" --exclude ".DS_Store" --exclude "ICTh/Vidios" \
  $SRCDIR "$DSTDIR"

echo Totale Grösse:
du -hs "$DSTDIR"

# EOF
