#!/bin/bash
########################################################################
#
# httpshare
# Simple share a file over HTTP
#
########################################################################

########################################################################
# Variabeln
FILE="$1"
PORT="${2:-8080}" # Use 8080 if $2 not set

########################################################################
# Functions
PrintUsage () {
  echo "Usage:
  httpshare file [port]"
}
ExitServer(){
  echo "Stop webserver"
  exit
}

########################################################################
# Main

trap ExitServer SIGINT SIGTERM

if [ "$#" -gt "2" ]
then
  PrintUsage
  exit 1
fi

if [ ! -r "$FILE" ]
then
  echo "File not readable"
  exit 1
fi

echo "Start webserver on port $PORT for file $FILE"

while true
do
   ( echo -e 'HTTP/1.1 200 OK\r\n'
     cat "$1"
   ) | nc -l "$PORT" || ExitServer
done

# EOF
