#!/bin/bash
#
# imageshrink - Shrink all images in the current directory
#
# TODO:
# - Images as Parameters
# - Resolution as Parameters
#

COUNT=0
TOTAL=`echo *.[Jj][Pp][Gg] | wc -w`

# Optionen
FOLDER="small"
SIZE="800x600"
SIZE="x1024"
SIZE="2048x2048"
SIZE="1024x1024"
SIZE="1280x1280"
QUALITY="75"

mkdir "$FOLDER"

for datei in *.[Jj][Pp][Gg]
do
  COUNT="`expr $COUNT + 1`"
  echo "$datei: Foto $COUNT von $TOTAL (`expr 100 \* $COUNT / $TOTAL`%)"
  convert -resize "$SIZE" -quality "$QUALITY" "$datei" "small/$datei" 
done
