#!/bin/bash
################################################################
#
# imagerotate
# Dreht Fotos anhand des EXIF-Tag Orientation
#
################################################################

########################################################################
# Main

if [ "$#" -eq "0" ]
then
  jhead -autorot *.[jJ][pP][gG]
else
  jhead -autorot $@
fi


# EOF
