#!/usr/bin/env bash
#
# Shows if internetconnection went down and up again
#

HOST="8.8.8.8"
STATUS="online"

while true
do
  if ping -c 1 "$HOST" &>/dev/null
  then
    NEWSTATUS="online"
  else
    NEWSTATUS="offline"
  fi

  if [[ "$NEWSTATUS" != "$STATUS" ]]
  then
    date "+%Y:%m:%d %H:%M:%S New status: $NEWSTATUS"
  fi

  STATUS="$NEWSTATUS"
  sleep 1m
done
