#!/usr/bin/env bash
#
# pic2vid
#
# Convert multiple pictures to a video (time lapse)
#
# Author: Emanuel Duss
#

DIR="$1"
PICDIR="pic2vid"
SMALLDIR="$DIR/$PICDIR"
SIZE="x1080"
QUALITY="90"
OUTPUTFILE="output.mpg"
CODEC="libx264"
FRAMESPERSECOND="25"

Printusage () {
  echo "Usage:
  $0 directory"
}

if [ -z "$1" ]
then
  Printusage
  exit 1
fi

if [ ! -d "$DIR" ]
then
  echo "$DIR ist kein Verzeichnis"
  Printusage
  exit 1
fi

if [ -d "$SMALLDIR" ]
then
  echo "Verzeichnis für aufzubereitende Fotos bereits vorhanden."
else
  mkdir "$SMALLDIR"
fi
if [ ! -d "$SMALLDIR" ]
then
  echo "Kann $SMALLDIR nicht anlegen. Bitte Berechtigungen prüfen."
  exit 1
fi

cd $DIR


TOTAL="`ls *.[Jj][Pp][Gg] | wc -l`"
COUNT="1"
for file in *.[Jj][Pp][Gg]
do
  if [ -f "${PICDIR}/$file" ]
  then
    echo "Überspringe $file, da bereits konvertiert (${PICDIR}/$file)"
  else
    echo "$file: Foto $COUNT von $TOTAL ($((100 * $COUNT / $TOTAL))%)"
    convert -resize $SIZE -quality $QUALITY "$file" "${PICDIR}/$file" 
  fi
  ((COUNT++))
done

# Rename pictures (like 0001.jpg to 2342.jpg)
cd $PICDIR
LENGTH="`ls *.[Jj][Pp][Gg] | wc -l | wc -L`"
NUMBER="1"
for file in *.[Jj][Pp][Gg]
do
  NEWNAME="`printf %0${LENGTH}d $NUMBER`.jpg"
  if [ -f "$NEWNAME" ]
  then
    echo "Datei $file bereits umbenannt. OK."
  else
    # Symlink statt umbenennen, damit die Prüfung ob schon konvertiert auch funktioniert
    ln -s "$file" "`printf %0${LENGTH}d $NUMBER`".jpg
  fi
  ((NUMBER++))
done

# create the video
ffmpeg -f image2 -i %0${LENGTH}d.jpg -r $FRAMESPERSECOND -vcodec $CODEC ../$OUTPUTFILE
