#!/bin/bash
#
# propersuspend - Script wich suspends the computer
#

if pgrep mpd >/dev/null 2>&1 && `which mpc` >/dev/null 2>&1
then
  mpc pause >/dev/null 2>&1
fi

for i in mplayer pmv vlc
do
  pkill $i >/dev/null 2>&1
done

i3lock -u --dpms -c 333333 --pointer default
systemctl suspend
