#!/bin/bash
######################################################################
#
# propersuspend
# Computer sauber in den Standby setzen
#
######################################################################

######################################################################
# Variabeln
LOCKCMD="i3lock -u --dpms -c 333333 --pointer default"
SUSPENDCMD="systemctl suspend"

######################################################################
# Main

if pgrep mpd >/dev/null 2>&1 && `which mpc` >/dev/null 2>&1
then
  mpc pause >/dev/null 2>&1
fi

pkill mplayer >/dev/null 2>&

$LOCKCMD
$SUSPENDCMD

# EOF
