#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

print_usage(){
  cat << EOI
Usage: qrscan

Select range or click into a window to scan the qrcode(s).

Depends on scrot and zbar.
EOI
}

check_dependencies(){
  local FAIL=0
  for tool in "$@"
  do
    if ! hash "$tool" &> /dev/null
    then
      echo "The tool $tool does not exist."
      FAIL=1
    fi
  done
  if [[ "$FAIL" == 1 ]]
  then
    exit 1
  fi
}

parse_arguments(){
  while getopts h name
  do
    case $name
    in
      h)
        print_usage
        exit
      ;;
      ?)
        print_usage >&2
        exit 1
      ;;
    esac
  done
}

cleanup(){
  if [[ -v "IMAGE" ]]
  then
    rm "$IMAGE"
  fi
}
trap cleanup EXIT

scan_qrcode(){
  IMAGE="$(mktemp --tmpdir="/tmp" scanqr_XXXXX.png)"
  if ! scrot -o -s "$IMAGE" 2>/dev/null
  then
    echo "Could not take image."
    exit 1
  fi

  if ! zbarimg -q --raw "$IMAGE"
  then
    echo "Could not read code."
    exit 1
  fi
}

main(){
  check_dependencies scrot zbarimg

  parse_arguments "$@"
  shift $((OPTIND - 1))

  scan_qrcode
}

main "$@"
