#!/bin/bash

set -o errexit
set -o pipefail

APP="feh -g 600x600+50%+50% --borderless --scale-down --image-bg checks"

print_usage(){
cat << EOI
Usage: screenshot [OPTION] [FILE]

By default, the selection is saved to your home directory.

Options:
  -f    fullscreen screenshot
  -c    copy selection to clipboard
  -h    display this help and exit

File:
  filename or directory where to save the screenshot.

EOI
}

check_dependencies(){
  local FAIL=0
  for tool in "$@"
  do
    if ! hash "$tool" &> /dev/null
    then
      echo "The tool $tool does not exist."
      FAIL=1
    fi
  done
  if [[ "$FAIL" == 1 ]]
  then
    exit 1
  fi
}

main(){
  check_dependencies maim

  case $1 in
    "full")
      FILENAME="$HOME/$(date +%Y-%m-%d_%H-%M-%S).png"
      maim "$FILENAME"
      $APP "$FILENAME"
    ;;
    "copy")
      check_dependencies xclip
      maim -s | xclip -selection clipboard -t image/png
    ;;
    *)
      FILENAME="$HOME/$(date +%Y-%m-%d_%H-%M-%S).png"
      maim -s "$FILENAME"
      $APP "$FILENAME"
    ;;
  esac
}

main "$@"
