#!/bin/bash
#
# securelv - Mount and umount a luks encrypted logical volume
#

NAME="backup"
MOUNTPATH="/media/$NAME"
LV="/dev/mapper/$NAME"

PrintUsage() {
  echo "Usage:
  securelv { mount | umount }"
}

case $1 in
  mount)
    echo cryptsetup luksOpen "$LV" "$NAME"
    cryptsetup luksOpen "$LV" "$NAME"
    echo mount /dev/mapper/secure "$MOUNTPATH"
    mount /dev/mapper/secure "$MOUNTPATH"
    ;;
  umount)
    echo umount "$MOUNTPATH"
    umount "$MOUNTPATH"
    echo cryptsetup luksClose "/dev/mapper/$NAME"
    cryptsetup luksClose "/dev/mapper/$NAME"
    ;;
  *)
    PrintUsage
    ;;
esac
