#!/bin/bash
########################################################################
#
# securelv
# Mount a LUKS encrypted Logical Volume
#
########################################################################

########################################################################
# Variabeln
NAME="backup"
MOUNTPATH="/media/$NAME"
LV="/dev/mapper/$NAME"

########################################################################
# Funktionen
PrintUsage() {
  echo "Usage:
  securelv { mount | umount }"
}

########################################################################
# Main
case $1 in
  mount)
    echo cryptsetup luksOpen "$LV" "$NAME"
    cryptsetup luksOpen "$LV" "$NAME"
    echo mount /dev/mapper/secure "$MOUNTPATH"
    mount /dev/mapper/secure "$MOUNTPATH"
    ;;
  umount)
    echo umount "$MOUNTPATH"
    umount "$MOUNTPATH"
    echo cryptsetup luksClose "/dev/mapper/$NAME"
    cryptsetup luksClose "/dev/mapper/$NAME"
    ;;
  *)
    PrintUsage
    ;;
esac

# EOF
