#!/usr/bin/env bash

exec xautolock -detectsleep \
  -time 5 -locker "i3lock -u --dpms -c 333333 --pointer default" \
  -notify 30 \
  -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'"

