#!/bin/bash
#
# getphotos - Get photos from a camera, rename and rotate
#

FOLDER="`date +GetPhotos_%Y-%m-%d`"

mkdir "$FOLDER"
cd "$FOLDER"

gphoto2 --get-all-files

jhead -autorot *.[jJ][pP][gG]
jhead -norot *.[jJ][pP][gG]

jhead -nf%Y-%m-%d_%H-%M-%S *.[jJ][pP][gG]

mkdir "`ls *.jpg | cut -c 1-10 | sort -u`"

ls *.jpg | cut -c 1-10 | sort -u | while read line
do
  mv "$line*.jpg" "$line"
done

cd ..
chown -R emanuel.users "$FOLDER"
