#!/usr/bin/env python
"""
template

This is a tempalte for python scripts.

Author: Emanuel Duss
"""

import argparse
import logging

def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('-x', '--xxx',metavar='file', required=True, dest='myvar', help='Somehelp')

    return parser.parse_args()

class MyClass:
    def __init__(self):
        print("Hello")

def main():
    args = parse_args()

    logger = logging.getLogger('simple_example')
    logger.setLevel(logging.DEBUG)
    logging.warning('Warning!')  # will print a message to the console

    myclass = MyClass()

    return

if __name__ == '__main__':
    main()
